# Generated by Django 4.1.1 on 2023-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='delivered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order_confirmed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order_pending',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order_placed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order_preparation_on_going',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='out_for_delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
