# Generated by Django 4.1.1 on 2023-03-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentStatus',
        ),
    ]
