# Generated by Django 4.1.1 on 2023-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0002_expiredtoken_created_at_usertoken_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredtoken',
            name='token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
