# Generated by Django 4.1.1 on 2023-03-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0002_remove_ordermaster_payment_status_orderdetail_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='products',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='price',
            new_name='product_price',
        ),
    ]
