# Generated by Django 4.1.1 on 2023-02-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0002_alter_orderstatus_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='payment_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.paymentstatus'),
        ),
    ]
