# Generated by Django 4.1.1 on 2023-03-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0003_rename_products_orderdetail_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_price',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.orderdetail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='products',
            field=models.ManyToManyField(through='BurgerApi.OrderProduct', to='BurgerApi.product'),
        ),
    ]
