# Generated by Django 4.1.1 on 2023-05-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0003_alter_expiredtoken_token_alter_usertoken_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='products',
            field=models.ManyToManyField(through='BurgerApi.OrderDetail', to='BurgerApi.product'),
        ),
    ]
