# Generated by Django 4.1.1 on 2023-02-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0004_alter_orderdetail_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='products',
        ),
    ]
