# Generated by Django 4.1.1 on 2023-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0004_remove_orderdetail_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='products',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='products',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
