# Generated by Django 4.1.1 on 2023-05-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0004_ordermaster_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='products',
        ),
    ]
