# Generated by Django 4.1.1 on 2023-03-21 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0005_remove_orderdetail_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product'),
            preserve_default=False,
        ),
    ]
