# Generated by Django 4.1.1 on 2023-02-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0005_rename_product_id_orderdetail_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='house_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='post_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
