# Generated by Django 4.1.1 on 2023-03-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0006_alter_orderdetail_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='products',
            new_name='product',
        ),
    ]
