# Generated by Django 4.1.1 on 2023-03-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0007_rename_products_orderdetail_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_master_id',
            new_name='order_master',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='BurgerApi.product'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order_master', 'product')},
        ),
    ]
