# Generated by Django 4.1.1 on 2023-02-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0007_remove_orderdetail_add_ons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
    ]
