# Generated by Django 4.1.1 on 2023-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0008_remove_orderdetail_add_ons_id_orderdetail_add_ons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='add_ons_price',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='add_ons',
            field=models.CharField(max_length=200),
        ),
    ]
