# Generated by Django 4.1.1 on 2023-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0008_rename_order_master_id_orderdetail_order_master_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_master',
            new_name='order_master_id',
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='products',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
    ]
