# Generated by Django 4.1.1 on 2023-03-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0010_remove_orderdetail_products_orderdetail_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_price',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
