# Generated by Django 4.1.1 on 2023-05-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0010_alter_orderdetail_add_ons'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='total_add_ons_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
