# Generated by Django 4.1.1 on 2023-03-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0011_rename_product_orderdetail_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
    ]
