# Generated by Django 4.1.1 on 2023-03-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0011_remove_userinfo_phone_remove_userinfo_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
