# Generated by Django 4.1.1 on 2023-03-24 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0012_alter_orderdetail_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product'),
        ),
    ]
