# Generated by Django 4.1.1 on 2023-05-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0013_alter_orderstatus_order_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order_master',
            new_name='order_master_id',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='customer_detail',
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='order_master_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_detail', to='BurgerApi.ordermaster'),
            preserve_default=False,
        ),
    ]
