# Generated by Django 4.1.1 on 2023-05-22 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0014_rename_order_master_orderstatus_order_master_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
