# Generated by Django 4.1.1 on 2023-05-22 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0018_rename_user_id_customerdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
