# Generated by Django 4.1.1 on 2023-05-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0020_rename_user_id_customerdetail_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='user',
            new_name='user_id',
        ),
    ]
