# Generated by Django 4.1.1 on 2023-05-23 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0022_alter_customerdetail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
